# The names shul and shul2 are like different services' url domain names, requests to which are redirected to their respective targetURLs: 
services:
  - domain: "shul"
    targetURLs:
      - "http://localhost:8001"
      - "http://localhost:8002"
    algorythm: "RoundRobin"

- domain: "shul2"
  targetURLs:
    - "http://localhost:8003"
    - "http://localhost:8004"
    - "http://localhost:8005"
  algorythm: "LeastConnections"
