# The names shul and shul2 are like different services' url domain names, requests to which are redirected to their respective targetURLs: 
api_port: 3000
listen_port: 8000
services:
  - name: "shul"
    domain: "shul:8000"
    targetURLs:
      - "http://localhost:8001"
      - "http://localhost:8002"
    algorythm: "RoundRobin"

  - name: "shul2"
    domain: "shul2:8000"
    targetURLs:
      - "http://localhost:8003"
      - "http://localhost:8004"
      - "http://localhost:8005"
    algorythm: "LeastConnections"
